import '../models/product.dart';

class AppConstants {
  static const String appName = 'DemoApp';
  static const String validUsername = 'emma@demoapp.com';
  static const String validPassword = '10203040';
  static const int pageSize = 6;

  static const List<String> categories = [
    'Casual',
    'Evening',
    'Party',
    'Boho',
  ];

  static const List<Product> products = [
    // === Casual (8) ===
    Product(id: 1, name: 'Floral Maxi Dress', description: 'Elegant floral print maxi dress with a flowy silhouette. Perfect for summer brunches and garden parties. Features a V-neckline and adjustable waist tie.', price: 89.99, iconCodePoint: 0xea0b, colorValue: 0xFFE91E63, availableColors: [0xFFE91E63, 0xFF9C27B0, 0xFF1565C0], imageAsset: 'assets/images/products/floral_maxi_dress.jpg', category: 'Casual'),
    Product(id: 2, name: 'Casual Sundress', description: 'Breezy cotton sundress with spaghetti straps and a tiered skirt. Soft pastel tones for a fresh everyday look. Machine washable for easy care.', price: 49.99, iconCodePoint: 0xea0b, colorValue: 0xFF42A5F5, availableColors: [0xFF42A5F5, 0xFFFFA726, 0xFFEF5350], imageAsset: 'assets/images/products/casual_sundress.jpg', category: 'Casual'),
    Product(id: 3, name: 'Shirt Dress', description: 'Classic button-down shirt dress with a relaxed fit. Rolled-up sleeves and a waist belt for a polished casual look. Great for office to evening.', price: 79.99, iconCodePoint: 0xea0b, colorValue: 0xFF5C6BC0, availableColors: [0xFF5C6BC0, 0xFF8D6E63, 0xFFEF5350], imageAsset: 'assets/images/products/shirt_dress.jpg', category: 'Casual'),
    Product(id: 4, name: 'White Linen Dress', description: 'Lightweight white linen dress with side pockets. Relaxed fit perfect for beach days and warm weather strolls. Breathable and effortlessly chic.', price: 64.99, iconCodePoint: 0xea0b, colorValue: 0xFFEEEEEE, availableColors: [0xFFEEEEEE, 0xFFE0F7FA, 0xFFFFF9C4], imageAsset: 'assets/images/products/white_linen_dress.jpg', category: 'Casual'),
    Product(id: 5, name: 'Denim Dress', description: 'Button-front denim dress with a modern silhouette. Versatile enough for weekend errands or a casual dinner. Pairs beautifully with sneakers or boots.', price: 74.99, iconCodePoint: 0xea0b, colorValue: 0xFF1565C0, availableColors: [0xFF1565C0, 0xFF42A5F5, 0xFF0D47A1], imageAsset: 'assets/images/products/denim_dress.jpg', category: 'Casual'),
    Product(id: 6, name: 'Yellow Sundress', description: 'Bright yellow cotton sundress with playful ruffles. A cheerful piece that brings sunshine to any occasion. Tiered skirt for extra movement.', price: 54.99, iconCodePoint: 0xea0b, colorValue: 0xFFFDD835, availableColors: [0xFFFDD835, 0xFFFFB74D, 0xFFFF8A65], imageAsset: 'assets/images/products/yellow_sundress.jpg', category: 'Casual'),
    Product(id: 7, name: 'Sage Midi Dress', description: 'Elegant sage green midi dress with front buttons. A calming earthy tone for a refined everyday look. Pairs well with sandals or heels.', price: 69.99, iconCodePoint: 0xea0b, colorValue: 0xFF689F38, availableColors: [0xFF689F38, 0xFF558B2F, 0xFF7CB342], imageAsset: 'assets/images/products/casual_sage_midi.jpg', category: 'Casual'),
    Product(id: 8, name: 'Rust Linen Dress', description: 'Minimalist rust orange linen dress with clean lines. Natural fabric that gets softer with every wash. Perfect for warm-weather layering.', price: 72.99, iconCodePoint: 0xea0b, colorValue: 0xFFBF360C, availableColors: [0xFFBF360C, 0xFF8D6E63, 0xFFA1887F], imageAsset: 'assets/images/products/casual_rust_linen.jpg', category: 'Casual'),

    // === Evening (8) ===
    Product(id: 9, name: 'Satin Evening Gown', description: 'Luxurious satin evening gown with a sweeping train. Features a draped bodice and side slit. Make a statement at your next formal event.', price: 249.99, iconCodePoint: 0xea0b, colorValue: 0xFF7B1FA2, availableColors: [0xFF7B1FA2, 0xFFC62828, 0xFF0D47A1], imageAsset: 'assets/images/products/satin_evening_gown.jpg', category: 'Evening'),
    Product(id: 10, name: 'Red Evening Dress', description: 'Stunning red silk evening dress with floor-length elegance. Sweetheart neckline and a flowing silhouette that commands attention at any gala.', price: 279.99, iconCodePoint: 0xea0b, colorValue: 0xFFC62828, availableColors: [0xFFC62828, 0xFFB71C1C, 0xFFD32F2F], imageAsset: 'assets/images/products/red_evening_dress.jpg', category: 'Evening'),
    Product(id: 11, name: 'Rose Satin Gown', description: 'Romantic rose pink satin ball gown with a full skirt. Perfect for proms, galas, and enchanted evenings. Features a fitted bodice with boning.', price: 299.99, iconCodePoint: 0xea0b, colorValue: 0xFFF48FB1, availableColors: [0xFFF48FB1, 0xFFCE93D8, 0xFFEF9A9A], imageAsset: 'assets/images/products/rose_satin_gown.jpg', category: 'Evening'),
    Product(id: 12, name: 'Burgundy Velvet Dress', description: 'Rich burgundy velvet midi dress with long sleeves. Sophisticated texture that catches the light beautifully. Ideal for winter formal occasions.', price: 189.99, iconCodePoint: 0xea0b, colorValue: 0xFF880E4F, availableColors: [0xFF880E4F, 0xFF4A148C, 0xFF1A237E], imageAsset: 'assets/images/products/burgundy_velvet_dress.jpg', category: 'Evening'),
    Product(id: 13, name: 'Peach Bridesmaid Dress', description: 'Elegant peach chiffon bridesmaid dress with delicate pleats. Floor-length with a flattering empire waist. Perfect for spring and summer weddings.', price: 159.99, iconCodePoint: 0xea0b, colorValue: 0xFFFFAB91, availableColors: [0xFFFFAB91, 0xFFF48FB1, 0xFFCE93D8], imageAsset: 'assets/images/products/peach_bridesmaid_dress.jpg', category: 'Evening'),
    Product(id: 14, name: 'Coral Maxi Dress', description: 'Flowing coral pink chiffon maxi dress with ethereal movement. Layered fabric creates a dreamy effect. A showstopper at sunset events.', price: 169.99, iconCodePoint: 0xea0b, colorValue: 0xFFFF7043, availableColors: [0xFFFF7043, 0xFFFF5722, 0xFFFF8A65], imageAsset: 'assets/images/products/coral_maxi_dress.jpg', category: 'Evening'),
    Product(id: 15, name: 'Champagne Gown', description: 'Dazzling champagne gold evening gown with subtle shimmer. Floor-length elegance for black-tie events. A timeless choice for the modern woman.', price: 319.99, iconCodePoint: 0xea0b, colorValue: 0xFFFFD54F, availableColors: [0xFFFFD54F, 0xFFFFC107, 0xFFFFB300], imageAsset: 'assets/images/products/evening_champagne_gown.jpg', category: 'Evening'),
    Product(id: 16, name: 'Mauve Silk Dress', description: 'Delicate mauve silk evening dress with a draped silhouette. Soft and romantic for special celebrations. Features a subtle V-back detail.', price: 229.99, iconCodePoint: 0xea0b, colorValue: 0xFFCE93D8, availableColors: [0xFFCE93D8, 0xFFBA68C8, 0xFFAB47BC], imageAsset: 'assets/images/products/evening_mauve_silk.jpg', category: 'Evening'),

    // === Party (8) ===
    Product(id: 17, name: 'Little Black Dress', description: 'A timeless little black dress with a flattering A-line cut. Sleeveless with a crew neckline. Your go-to for cocktail parties and evening events.', price: 129.99, iconCodePoint: 0xea0b, colorValue: 0xFF212121, availableColors: [0xFF212121, 0xFF880E4F, 0xFF1A237E], imageAsset: 'assets/images/products/little_black_dress.jpg', category: 'Party'),
    Product(id: 18, name: 'Lace Cocktail Dress', description: 'Romantic lace overlay cocktail dress with scalloped hemline. Fitted bodice with a flared skirt. Fully lined for comfort.', price: 159.99, iconCodePoint: 0xea0b, colorValue: 0xFFAD1457, availableColors: [0xFFAD1457, 0xFFF5F5F5, 0xFF000000], imageAsset: 'assets/images/products/lace_cocktail_dress.jpg', category: 'Party'),
    Product(id: 19, name: 'Gold Party Dress', description: 'Dazzling gold metallic party dress with all-over sparkle. Mini length for maximum impact on the dance floor. Spaghetti straps and a flared skirt.', price: 139.99, iconCodePoint: 0xea0b, colorValue: 0xFFFFD54F, availableColors: [0xFFFFD54F, 0xFFFFC107, 0xFFFFB300], imageAsset: 'assets/images/products/gold_party_dress.jpg', category: 'Party'),
    Product(id: 20, name: 'Navy Cocktail Dress', description: 'Glamorous navy blue sequin cocktail dress. Short length with shimmering detail that catches every light. Perfect for New Year celebrations.', price: 149.99, iconCodePoint: 0xea0b, colorValue: 0xFF1A237E, availableColors: [0xFF1A237E, 0xFF283593, 0xFF303F9F], imageAsset: 'assets/images/products/navy_cocktail_dress.jpg', category: 'Party'),
    Product(id: 21, name: 'Black Sequin Mini', description: 'Show-stopping black sequin mini dress. Sleeveless design with head-to-toe sparkle. The ultimate party piece for unforgettable nights out.', price: 119.99, iconCodePoint: 0xea0b, colorValue: 0xFF212121, availableColors: [0xFF212121, 0xFF424242, 0xFF616161], imageAsset: 'assets/images/products/black_sequin_mini.jpg', category: 'Party'),
    Product(id: 22, name: 'Mint Cocktail Dress', description: 'Fresh mint green fit-and-flare cocktail dress. Flattering silhouette with a nipped waist and full skirt. A refreshing choice for spring events.', price: 109.99, iconCodePoint: 0xea0b, colorValue: 0xFF80CBC4, availableColors: [0xFF80CBC4, 0xFF4DB6AC, 0xFF26A69A], imageAsset: 'assets/images/products/mint_cocktail_dress.jpg', category: 'Party'),
    Product(id: 23, name: 'Copper Sequin Dress', description: 'Warm copper bronze sequin dress that glows under any light. A unique alternative to gold or silver. Perfect for autumn celebrations.', price: 134.99, iconCodePoint: 0xea0b, colorValue: 0xFFBF360C, availableColors: [0xFFBF360C, 0xFF8D6E63, 0xFFA1887F], imageAsset: 'assets/images/products/party_copper_sequin.jpg', category: 'Party'),
    Product(id: 24, name: 'Rose Gold Mini', description: 'Romantic rose gold metallic mini dress. Delicate shimmer for a feminine party look. Pairs perfectly with strappy heels and statement earrings.', price: 124.99, iconCodePoint: 0xea0b, colorValue: 0xFFF48FB1, availableColors: [0xFFF48FB1, 0xFFCE93D8, 0xFFEF9A9A], imageAsset: 'assets/images/products/party_rose_gold.jpg', category: 'Party'),

    // === Boho (8) ===
    Product(id: 25, name: 'Boho Wrap Dress', description: 'Free-spirited bohemian wrap dress with artistic print. Adjustable wrap closure for a custom fit. Lightweight fabric ideal for warm days.', price: 69.99, iconCodePoint: 0xea0b, colorValue: 0xFFFF7043, availableColors: [0xFFFF7043, 0xFF26A69A, 0xFFAB47BC], imageAsset: 'assets/images/products/boho_wrap_dress.jpg', category: 'Boho'),
    Product(id: 26, name: 'Pleated Midi Skirt', description: 'Graceful pleated midi skirt with an elastic waistband. Pairs beautifully with blouses and tucked-in tops. Available in stunning jewel tones.', price: 59.99, iconCodePoint: 0xea0b, colorValue: 0xFF26A69A, availableColors: [0xFF26A69A, 0xFFEC407A, 0xFF5C6BC0], imageAsset: 'assets/images/products/pleated_midi_skirt.jpg', category: 'Boho'),
    Product(id: 27, name: 'Terracotta Boho Dress', description: 'Earthy terracotta maxi dress with intricate embroidery. Tiered skirt with bohemian fringe details. A free-spirited piece for music festivals.', price: 99.99, iconCodePoint: 0xea0b, colorValue: 0xFFBF360C, availableColors: [0xFFBF360C, 0xFF8D6E63, 0xFFA1887F], imageAsset: 'assets/images/products/terracotta_boho_dress.jpg', category: 'Boho'),
    Product(id: 28, name: 'Emerald Wrap Dress', description: 'Stunning emerald green wrap dress with a flattering tie waist. Knee-length with a graceful drape. Transitions effortlessly from day to night.', price: 84.99, iconCodePoint: 0xea0b, colorValue: 0xFF2E7D32, availableColors: [0xFF2E7D32, 0xFF1B5E20, 0xFF4CAF50], imageAsset: 'assets/images/products/emerald_wrap_dress.jpg', category: 'Boho'),
    Product(id: 29, name: 'Lavender Tulle Skirt', description: 'Dreamy lavender tulle midi skirt with multiple layers. Creates a fairy-tale silhouette for special occasions. Elastic waistband for comfort.', price: 69.99, iconCodePoint: 0xea0b, colorValue: 0xFFCE93D8, availableColors: [0xFFCE93D8, 0xFFBA68C8, 0xFFAB47BC], imageAsset: 'assets/images/products/lavender_tulle_skirt.jpg', category: 'Boho'),
    Product(id: 30, name: 'Olive Shirt Dress', description: 'Military-inspired olive green shirt dress with structured details. Belted waist and chest pockets for a utilitarian chic aesthetic.', price: 89.99, iconCodePoint: 0xea0b, colorValue: 0xFF689F38, availableColors: [0xFF689F38, 0xFF558B2F, 0xFF7CB342], imageAsset: 'assets/images/products/olive_shirt_dress.jpg', category: 'Boho'),
    Product(id: 31, name: 'Crochet White Dress', description: 'Delicate white crochet boho dress with intricate lacework. A stunning piece for beach weddings or summer festivals. Fully lined underneath.', price: 94.99, iconCodePoint: 0xea0b, colorValue: 0xFFFAFAFA, availableColors: [0xFFFAFAFA, 0xFFEEEEEE, 0xFFF5F5F5], imageAsset: 'assets/images/products/boho_crochet_white.jpg', category: 'Boho'),
    Product(id: 32, name: 'Turquoise Print Dress', description: 'Vibrant turquoise tribal print maxi dress. Bold patterns inspired by global textiles. A statement piece for the adventurous fashionista.', price: 79.99, iconCodePoint: 0xea0b, colorValue: 0xFF00897B, availableColors: [0xFF00897B, 0xFF00695C, 0xFF26A69A], imageAsset: 'assets/images/products/boho_turquoise_print.jpg', category: 'Boho'),
  ];
}
